# Numerical Python

In [1]:
import numpy as np

In [2]:
x = np.array ([3, 4, 5])
y = np.array ([4, 9, 7])

In [3]:
x + y

array([ 7, 13, 12])

In [4]:
x = np.array ([[1, 2], [3, 4]])
x

array([[1, 2],
       [3, 4]])

In [5]:
x.ndim

2

In [6]:
x.dtype

dtype('int64')

In [7]:
np.array ([[1, 2], [3.0, 4]]).dtype

dtype('float64')

In [9]:
np.array ([[1, 2], [3, 4]], float).dtype

dtype('float64')

In [10]:
x.shape

(2, 2)

In [11]:
x = np.array ([1, 2, 3, 4])
np.sum(x)

10

In [12]:
x = np.array ([1, 2, 3, 4, 5, 6])
print('beginning x:\n', x)
x_reshape = x.reshape ((2, 3))
print('reshaped x:\n', x_reshape)

beginning x:
 [1 2 3 4 5 6]
reshaped x:
 [[1 2 3]
 [4 5 6]]


In [13]:
x_reshape [0, 0]

1

In [14]:
x_reshape [1, 2]

6

In [15]:
print('x before we modify x_reshape :\n', x)
print('x_reshape before we modify x_reshape :\n', x_reshape)
x_reshape [0, 0] = 5
print('x_reshape after we modify its top left element :\n',
x_reshape)
print('x after we modify top left element of x_reshape :\n', x)

x before we modify x_reshape :
 [1 2 3 4 5 6]
x_reshape before we modify x_reshape :
 [[1 2 3]
 [4 5 6]]
x_reshape after we modify its top left element :
 [[5 2 3]
 [4 5 6]]
x after we modify top left element of x_reshape :
 [5 2 3 4 5 6]


In [16]:
x_reshape.shape , x_reshape.ndim , x_reshape.T

((2, 3),
 2,
 array([[5, 4],
        [2, 5],
        [3, 6]]))

In [17]:
np.sqrt(x)

array([2.23606798, 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974])

In [18]:
x**2

array([25,  4,  9, 16, 25, 36])

In [19]:
x**0.5

array([2.23606798, 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974])

In [20]:
x = np.random.normal(size =50)
x

array([ 0.1917456 ,  0.06839631, -0.79202755, -0.19565405, -0.79793428,
        0.63382211,  1.61828353, -0.38051763,  0.3590475 , -1.52779062,
        0.33551371, -0.38497161, -0.36001123, -2.78879857,  0.65195377,
        1.92156065,  1.74439944,  0.52760532, -1.7250737 ,  0.62506206,
       -2.5874288 ,  0.86225899,  1.69754066,  1.20813451, -0.85056433,
        0.23966773,  0.30308158, -1.28701288,  0.73486545,  1.46059532,
        1.20473002, -0.0080212 ,  0.602999  , -0.27729639,  0.62863592,
        1.27690496,  0.71012734, -0.60136837, -2.06461417,  2.15928085,
        0.56274368, -0.78319211, -1.28189495,  0.03934104,  2.02114658,
        1.67948909, -0.58747559, -2.52707647,  0.7596975 ,  0.67758626])

In [21]:
y = x + np.random.normal(loc=50, scale=1, size =50)

In [22]:
np.corrcoef(x, y)

array([[1.        , 0.78271593],
       [0.78271593, 1.        ]])

In [26]:
print(np.random.normal(scale=5,size =2))
print(np.random.normal(scale=5,size =2))

[-8.35320064  5.98535099]
[-6.81821128  8.95198434]


### We use a default seed for the rng

In [27]:
rng = np.random.default_rng (1303)
print(rng.normal(scale=5, size =2))
rng2 = np.random.default_rng (1303)
print(rng2.normal(scale=5, size =2))

[ 4.09482632 -1.07485605]
[ 4.09482632 -1.07485605]


In [28]:
rng = np.random.default_rng (3)
y = rng.standard_normal (10)
np.mean(y), y.mean ()

(-0.1126795190952861, -0.1126795190952861)

In [29]:
np.var(y), y.var(), np.mean ((y - y.mean ())**2)

(2.7243406406465125, 2.7243406406465125, 2.7243406406465125)

In [30]:
X = rng.standard_normal ((10, 3))
X

array([[ 0.22578661, -0.35263079, -0.28128742],
       [-0.66804635, -1.05515055, -0.39080098],
       [ 0.48194539, -0.23855361,  0.9577587 ],
       [-0.19980213,  0.02425957,  1.54582085],
       [ 0.54510552, -0.50522874, -0.18283897],
       [ 0.54052513,  1.93508803, -0.26962033],
       [-0.24355868,  1.0023136 , -0.88645994],
       [-0.29172023,  0.88253897,  0.58035002],
       [ 0.0915167 ,  0.67010435, -2.82816231],
       [ 1.02130682, -0.95964476, -1.66861984]])

In [31]:
X.mean(axis =0)

array([ 0.15030588,  0.14030961, -0.34238602])

In [32]:
X.mean(0)

array([ 0.15030588,  0.14030961, -0.34238602])