# Indexing Data

In [59]:
A = np.array(np.arange (16)).reshape ((4, 4))
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [60]:
A[1,2]

6

In [61]:
A[[1 ,3]]

array([[ 4,  5,  6,  7],
       [12, 13, 14, 15]])

In [62]:
A[: ,[0 ,2]]

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14]])

In [64]:
A[[1 ,3]][: ,[0 ,2]]

array([[ 4,  6],
       [12, 14]])

Another way of extracting a submatrix that is more efficient is using `np.ix_()`

In [65]:
idx = np.ix_ ([1 ,3] ,[0 ,2 ,3])
A[idx]

array([[ 4,  6,  7],
       [12, 14, 15]])

In [66]:
A[1:4:2 ,0:3:2]

array([[ 4,  6],
       [12, 14]])

### **Boolean Indexing**

In [67]:
keep_rows = np.zeros(A.shape [0], bool)
keep_rows

array([False, False, False, False])

In [68]:
keep_rows [[1 ,3]] = True
keep_rows

array([False,  True, False,  True])

In [69]:
np.all(keep_rows == np.array ([0 ,1 ,0 ,1]))

True

In [70]:
A[np.array ([0 ,1 ,0 ,1])]

array([[0, 1, 2, 3],
       [4, 5, 6, 7],
       [0, 1, 2, 3],
       [4, 5, 6, 7]])

In [71]:
A[keep_rows]

array([[ 4,  5,  6,  7],
       [12, 13, 14, 15]])

In [73]:
keep_cols = np.zeros(A.shape[1], bool)
keep_cols[[0, 2, 3]] = True
idx_bool = np.ix_(keep_rows , keep_cols)
A[idx_bool]

array([[ 4,  6,  7],
       [12, 14, 15]])

In [74]:
idx_mixed = np.ix_ ([1,3], keep_cols)
A[idx_mixed]

array([[ 4,  6,  7],
       [12, 14, 15]])